version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: curso
    #restart: always
    depends_on:
      - db-videojuegos
    ports:
      - 8000:8000
    volumes: 
      - ./videojuegos/:/app

  db-videojuegos:
    image: mariadb
    container_name: videojuegos-db
    #restart: always
    environment:
      MYSQL_DATABASE: videojuegos
      MYSQL_USER: videojuegos_user
      MYSQL_PASSWORD: "asjdghj"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-videojuegos:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db:    
  db-videojuegos:    

