# Generated by Django 4.0.2 on 2022-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('decripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('1', 'Acción'), ('2', 'Aventura'), ('3', 'Carrera')], max_length=1, verbose_name='Género')),
            ],
        ),
    ]
