# Generated by Django 4.0.2 on 2022-03-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_categoria_articulos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
